export const carData = [
  {
    id: 1,
    brand: "Toyota",
    model: "Camry",
    category: "Sedan",
    imageUrl: "https://images.unsplash.com/photo-1588440983028-d53e24fa96cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dG95b3RhJTIwY2Ftcnl8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 50,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.5,
    description: "The Toyota Camry is a reliable sedan that offers a smooth ride and excellent fuel efficiency. With its spacious interior and advanced safety features, it's perfect for both city commuting and long trips. Enjoy the comfort and dependability that the Camry is known for."
  },
  {
    id: 2,
    brand: "Honda",
    model: "Civic",
    category: "Sedan",
    imageUrl: "https://images.unsplash.com/photo-1610768207795-72169abdf0d4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvbmRhJTIwY2l2aWN8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 45,
    seatingCapacity: 5,
    transmission: "Manual",
    fuelType: "Diesel",
    location: "Lalibela",
    rating: 4.0,
    description: "The Honda Civic is a compact sedan that combines style, comfort, and efficiency. With its sporty design and advanced technology features, it's perfect for urban driving and daily commutes."
  },
  {
    id: 3,
    brand: "Ford",
    model: "Explorer",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1696233016051-55a6fd6b03e5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Zm9yZCUyMGV4cGxvcmVyfGVufDB8fDB8fHww",
    pricePerDay: 70,
    seatingCapacity: 7,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Gondar",
    rating: 4.8,
    description: "The Ford Explorer is a spacious SUV that offers a comfortable ride and plenty of cargo space. With its powerful engine and advanced safety features, it's perfect for family trips and outdoor adventures."
  },
  {
    id: 4,
    brand: "Chevrolet",
    model: "Tahoe",
    category: "SUV",
    imageUrl: "https://www.chevrolet.com/content/dam/chevrolet/na/us/english/vdc-collections/2025/suvs/tahoe/nav/02-images/2025-tahoe-2z7-gbd-driver-front-3quarter-nav.jpg?imwidth=1920",
    pricePerDay: 80,
    seatingCapacity: 11,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Axum",
    rating: 4.6,
    description: "The Chevrolet Tahoe is a full-size SUV that offers a spacious interior and a smooth ride. With its powerful V8 engine and advanced technology features, it's perfect for families and adventurers alike."
  },
  {
    id: 5,
    brand: "Nissan",
    model: "Rogue",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fG5pc3NhbnxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 75,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.4,
    description: "The Nissan Rogue is a compact SUV that offers a comfortable ride and plenty of cargo space. With its advanced safety features and fuel-efficient engine, it's perfect for both city driving and weekend getaways."
  },
  {
    id: 6,
    brand: "Hyundai",
    model: "Tucson",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1646728502468-06d9c7b3c2c2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aHl1bmRhaXxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 65,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Lalibela",
    rating: 4.7,
    description: "The Hyundai Tucson is a compact SUV that offers a comfortable ride and a well-designed interior. With its advanced safety features and user-friendly technology, it's perfect for families and urban adventures."
  },
  {
    id: 7,
    brand: "Kia",
    model: "Sportage",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1625037669075-e5472e080265?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGtpYXxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 70,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Axum",
    rating: 4.5,
    description: "The Kia Sportage is a compact SUV that offers a comfortable ride and a spacious interior. With its advanced safety features and user-friendly technology, it's perfect for families and urban adventures."
  },
  {
    id: 8,
    brand: "Mazda",
    model: "CX-5",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1643142314755-672bd62b0fe6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fG1hemRhfGVufDB8fDB8fHww",
    pricePerDay: 75,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Gondar",
    rating: 4.6,
    description: "The Mazda CX-5 is a compact SUV that offers a stylish design and a comfortable interior. With its responsive handling and advanced safety features, it's perfect for both city driving and outdoor adventures."
  },
  {
    id: 9,
    brand: "Subaru",
    model: "Outback",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1458531534615-e81e99962807?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHN1YmFydXxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 80,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.7,
    description: "The Subaru Outback is a rugged SUV that offers excellent off-road capability and a spacious interior. With its standard all-wheel drive and advanced safety features, it's perfect for adventurous families."
  },
  {
    id: 10,
    brand: "Volkswagen",
    model: "Tiguan",
    category: "VAN",
    imageUrl: "https://images.unsplash.com/photo-1626816442078-8fac6017f791?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHZvbGtzd2FnZW58ZW58MHx8MHx8fDA%3D",
    pricePerDay: 85,
    seatingCapacity: 11,
    transmission: "Manual",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.6,
    description: "The Volkswagen Tiguan is a versatile and spacious SUV that offers a comfortable ride and advanced technology features. With its flexible seating and cargo options, it's perfect for families and outdoor enthusiasts."
  },
  {
    id: 11,
    brand: "Tesla",
    model: "Model X",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGVzbGF8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 120,
    seatingCapacity: 7,
    transmission: "Automatic",
    fuelType: "Electric",
    location: "Gondar",
    rating: 4.9,
    description: "The Tesla Model X is a luxury electric SUV that offers impressive performance and cutting-edge technology. With its spacious interior and advanced safety features, it's perfect for families and eco-conscious drivers."
  },
  {
    id: 12,
    brand: "Porsche",
    model: "Cayenne",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1597858520171-563a8e8b9925?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHBvcnNjaGV8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 150,
    seatingCapacity: 2,
    transmission: "Hybrid",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.8,
    description: "The Porsche Cayenne is a high-performance luxury SUV that combines power and elegance. With its spacious interior and advanced technology features, it's perfect for those who demand the best."
  },
  {
    id: 13,
    brand: "BMW",
    model: "X5",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1607853554439-0069ec0f29b6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ym13fGVufDB8fDB8fHww",
    pricePerDay: 140,
    seatingCapacity: 7,
    transmission: "Hybrid",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.7,
    description: "The BMW X5 is a luxury SUV that offers a perfect blend of performance, comfort, and technology. With its spacious interior and advanced safety features, it's ideal for families and long journeys."
  },
  {
    id: 14,
    brand: "Mercedes-Benz",
    model: "G-Class",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1lcmNlZGVzJTIwYmVuenxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 200,
    seatingCapacity: 2,
    transmission: "Manual",
    fuelType: "Petrol",
    location: "Lalibela",
    rating: 4.9,
    description: "The Mercedes-Benz G-Class is a luxury SUV known for its rugged off-road capability and high-end interior. With its iconic design and advanced technology features, it's perfect for those who want to make a statement."
  },
  {
    id: 15,
    brand: "Lexus",
    model: "RX",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1615106806531-183c31fccfdc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGV4dXN8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 130,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.8,
    description: "The Lexus RX is a luxury SUV that offers a comfortable ride and a spacious interior. With its advanced safety features and cutting-edge technology, it's perfect for families and those who appreciate the finer things in life."
  },
  {
    id: 16,
    brand: "Jaguar",
    model: "F-PACE",
    category: "SUV",
    imageUrl: "https://images.unsplash.com/photo-1575496917055-f23c822796eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGphZ3VhciUyMGNhcnxlbnwwfHwwfHx8MA%3D%3D",
    pricePerDay: 160,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Axum",
    rating: 4.8,
    description: "The Jaguar F-PACE is a luxury SUV that combines performance, style, and practicality. With its spacious interior and advanced technology features, it's perfect for those who want a versatile and stylish vehicle."
  },
  {
    id: 17,
    brand: "Toyota",
    model: "Camry",
    category: "Sedan",
    imageUrl: "https://images.unsplash.com/photo-1588440983028-d53e24fa96cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dG95b3RhJTIwY2Ftcnl8ZW58MHx8MHx8fDA%3D",
    pricePerDay: 50,
    seatingCapacity: 5,
    transmission: "Automatic",
    fuelType: "Petrol",
    location: "Addis Ababa",
    rating: 4.5,  
    description: "The Toyota Camry is a reliable sedan that offers a smooth ride and excellent fuel efficiency. With its spacious interior and advanced safety features, it's perfect for both city commuting and long trips. Enjoy the comfort and dependability that the Camry is known for."
  }
];
